export const BLUR_IMAGE =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mOcXg8AAbMBGIpVIK8AAAAASUVORK5CYII='
export const POPULAR_POST_LENGTH = 4
export const DATE_FORMAT = 'D MMMM YYYY'
